[package]
name = "breaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
macroquad = "0.3.23"
macroquad-canvas = "0.3.0"
bevy_ecs = "0.8.1"
